### ISSUE TITLE
For the (-i) option you specified a location which doesn't exist or is not readable

### ISSUE THREAD

**Issue by sajjadasaf** [Micromeda/InterProScan-Docker#14]
Hello,
I tried to run InterProScan but faced the following error. Could you kindly guide me what is the problem.
Thank you

command:
docker run --rm --name interproscan -v /tmp:/tmp micromeda/interproscan-docker -dp --goterms --pathways -f tsv --appl "PfamA,TIGRFAM,PRINTS,PrositePatterns,Gene3d" -o /tmp/out.ipr -i /tmp/fungap_out_prot.faa

Adjusting interproscan.properties file to take into account that there are 48 cores.
Setting max ipr5 workers to 24.
Setting starting ipr5 workers to 12.
Setting number if CPU cores for jobs to 2.

07/01/2021 18:32:09:974 Welcome to InterProScan-5.27-66.0
For the (-i) option you specified a location which doesn't exist or is not readable:
/tmp/fungap_out_prot.faa

**Comment by LeeBergstrand** [comment]
@sajjadasaf Do you still need help with this?

**Comment by LeeBergstrand** [comment]
@sajjadasaf It might be because either docker or your user does not have permission to read or write to the temp directory.
