### ISSUE TITLE
Include genome properties in the docker

### ISSUE THREAD

**Issue by SilasK** [Micromeda/InterProScan-Docker#3]
Hey @LeeBergstrand Do you think it would be possible to include the genome properties in the docker. I have a hard time to install the perm modules needed to run the genome properties scripts.

**Comment by LeeBergstrand** [comment]
https://github.com/Micromeda/genome-properties?files=1

Check out our fork of genome-properties.

Already done!

**Comment by SilasK** [comment]
Great you made my day.
